apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: address-privateserviceaccess
spec:
  addressType: INTERNAL
  location: global
  purpose: VPC_PEERING
  prefixLength: 16 # kpt-set: ${prefix-length}
  networkRef:
    name: vpc-privateserviceaccess
