apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: "abandon"
    cnrm.cloud.google.com/disable-dependent-services: "false"
  name: project-id-servicenetworking # kpt-set: ${project-id}-servicenetworking
spec:
  resourceID: servicenetworking.googleapis.com
