---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: containercluster-vpcnative-network # kpt-set: ${network-name}
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: containercluster-vpcnative-subnetwork # kpt-set: ${subnetwork-name}
spec:
  ipCidrRange: 10.2.0.0/16
  region: asia-northeast1 # kpt-set: ${cluster-location}
  networkRef:
    name: containercluster-vpcnative-network # kpt-set: ${network-name}
  secondaryIpRange:
  - rangeName: servicesrange
    ipCidrRange: 10.3.0.0/16
  - rangeName: clusterrange
    ipCidrRange: 10.4.0.0/16