apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecretVersion
metadata:
  name: secret-version-sample
spec:
  enabled: true
  secretData:
    valueFrom:
      secretKeyRef:
        key: key-sample
        name: secret-sample
  secretRef:
    name: test-secret # kpt-set: ${secret-manager-secret-name}
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-sample
data:
  keySample: SSBhbHdheXMgbG92ZWQgc3BhcnJpbmcgd2l0aCBnaWFudCBjYW5keSBzd29yZHMsIGJ1dCBJIGhhZCBubyBpZGVhIHRoYXQgd2FzIG15IHN1cGVyIHNlY3JldCBpbmZvcm1hdGlvbiE=
---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  name: test-secret # kpt-set: ${secret-manager-secret-name}
spec:
  replication:
    automatic: true
