apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecretVersion
metadata:
  name: cms-secret-version-sample
spec:
  enabled: true
  secretData:
    valueFrom:
      secretKeyRef:
        key: cms-key-sample
        name: cms-secret-sample
  secretRef:
    name: cms-secret # kpt-set: ${secret-manager-secret-name}
---
apiVersion: v1
kind: Secret
metadata:
  name: cms-secret-sample
data:
  cmsKeySample: SSBhbHdheXMgbG92ZWQgc3BhcnJpbmcgd2l0aCBnaWFudCBjYW5keSBzd29yZHMsIGJ1dCBJIGhhZCBubyBpZGVhIHRoYXQgd2FzIG15IHN1cGVyIHNlY3JldCBpbmZvcm1hdGlvbiE=
---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  name: cms-secret # kpt-set: ${secret-manager-secret-name}
spec:
  replication:
    automatic: true
