apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: test-db # kpt-set: ${dbname}
spec:
  databaseVersion: MYSQL_5_7 # kpt-set: ${database-version}
  region: asia-northeast1 # kpt-set: ${region}
  settings:
    tier: db-f1-micro # kpt-set: ${tier}
    availabilityType: REGIONAL
    backupConfiguration:
      binaryLogEnabled: true
      enabled: true
