---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstanceGroupManager
metadata:
  name: compute-instancegroupmanager # kpt-set: ${instance-group-manager-name}
spec:
  projectRef:
    external: "projects/test-project" # kpt-set: projects/${project-id}
  location: asia-northeast1 # kpt-set: ${compute-location}
  baseInstanceName: app
  autoHealingPolicies:
    - healthCheckRef:
        name: compute-healthcheck # kpt-set: ${healthcheck-name}
      initialDelaySec: 300
  targetSize: 3
  instanceTemplateRef:
    name: compute-instance-template # kpt-set: ${instance-template-name}
  updatePolicy:
    instanceRedistributionType: PROACTIVE
    minimalAction: RESTART
    maxSurge:
      fixed: 3
    maxUnavailable:
      fixed: 3
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstanceTemplate
metadata:
  name: compute-instance-template # kpt-set: ${instance-template-name}
spec:
  machineType: n1-standard-1
  disk:
  - sourceImageRef:
      external: debian-cloud/debian-9
    boot: true
  networkInterface:
  - networkRef:
      name: compute-network # kpt-set: ${network-name}
    subnetworkRef:
      name: compute-subnetwork # kpt-set: ${subnetwork-name}