---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: compute-network # kpt-set: ${network-name}
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: compute-subnetwork # kpt-set: ${subnetwork-name}
spec:
  ipCidrRange: 10.2.0.0/16
  region: asia-northeast1 # kpt-set: ${compute-location}
  networkRef:
    name: compute-network # kpt-set: ${network-name}
  privateIpGoogleAccess: false