apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
  name: project-id-static-contents # kpt-set: ${project-id}-static-contents
spec:
  uniformBucketLevelAccess: true # kpt-set: ${uniform-bucket-level-access}
  storageClass: standard # kpt-set: ${storage-class}
  location: asia-northeast1 # kpt-set: ${bucket-location}
  lifecycleRule:
    - action:
        type: Delete
      condition:
        age: 7
  versioning:
    enabled: true # kpt-set: ${enable-versioning}
