apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: "abandon"
    cnrm.cloud.google.com/disable-dependent-services: "false"
  name: project-id-cloudstorage # kpt-set: ${project-id}-cloudstorage
spec:
  resourceID: storage.googleapis.com
